# Site settings
title: Ashwin Madavan
header-img: img/home-bg.jpg
email: ashwin.madavan@gmail.com
description: "The work and thoughts of a programmer"
baseurl: ""
url: "http://ashwin153.github.io"
twitter_username:
github_username:  ashwin153
facebook_username:  ashwin.madavan

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
